version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdms-backend-dev
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=86.107.198.48
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=akzhol2030
      - POSTGRES_DB=karatobe
      - SECRET_KEY=sfgwerthggrnbsdfvstghernsdfvaergfv34g2rbvsdfv
      - ENVIRONMENT=development
      - DEBUG=true
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    restart: unless-stopped
    networks:
      - pdms-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdms-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_API_BASE_PATH=/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - pdms-network

volumes:
  backend_uploads:
  backend_logs:

networks:
  pdms-network:
    driver: bridge