#version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: karatobe_postgres
    environment:
      POSTGRES_DB: karatobe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akzhol2030
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: